### ISSUE TITLE
EigenVector to Function.vector()

### ISSUE THREAD

**Issue by arthbous** [thepnpsolver/modular-pnp#10]
In master/fast_to_fenics:

Trouble to assign EigenVector.vec() to a Function.vector()

See test_fasptofenics.cpp line 150.

**Comment by maximilianmetti** [comment]
What's the error?  Segfault?

**Comment by arthbous** [comment]
no error anymore, it's all good.

I think it does the trick

**Comment by maximilianmetti** [comment]
Why do you keep closing this PR??

**Comment by arthbous** [comment]
Because I never wanted to start the issue in the first place, I though it
was a comment thingy..

I am new to GitHub dude..so chillax...

**Comment by maximilianmetti** [comment]
i see... this isn't the PR.  This is an issue.  hehe ; )
