### ISSUE TITLE
EAFE

### ISSUE THREAD

**Issue by arthbous** [thepnpsolver/modular-pnp#55]
[Lines](https://github.com/thepnpsolver/modular-pnp/blob/master/include/EAFE.h#L1694-L1695) :
`double fermi_r = w[0][r] - w[2][r];`
` double fermi_s = w[0][s] - w[2][s];`
I would have changed them to:
`double fermi_r = w[2][r];`
` double fermi_s = w[2][s];`
then I would have change [line](https://github.com/thepnpsolver/modular-pnp/blob/master/include/EAFE.h#L1698) to
` double alpha_E = 0.5*(w[1][r]*std::exp(w[0][r])+w[1][s]*std::exp(w[0][s]))*std::exp(fermi_s);`

@maximilianmetti

**Comment by arthbous** [comment]
@https://github.com/thepnpsolver/modular-pnp/blob/master/include/EAFE.h#L1694-L1695

**Comment by maximilianmetti** [comment]
so, what is the question again?

**Comment by maximilianmetti** [comment]
can we close this issue?

**Comment by arthbous** [comment]
yes
